baseURL = "https://www.dataday.life"
languageCode = "en-us"
title = "Data-Day Life"
theme = "berbera"

pygmentsCodeFences = true
pygmentsUseClasses = true
canonifyURLs = true
publishDir = "public"
disableKinds = []
publisDir = "docs"
disqusShortname = "https://datadaylife.disqus.com"