baseURL = "https://www.andrewcbancroft.com"
languageCode = "en-us"
title = "Andrew Bancroft"
description = 'Sharing bits of what I&#039;m learning one byte at a time.'
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = []
disqusShortname="andrewcbancroft"